---
apiVersion: kubara.io/v1alpha1
kind: ServiceDefinition
metadata:
  name: argocd
  annotations:
    kubara.io/category: application-management
spec:
  chartPath: argo-cd
  status: disabled
  clusterTypes:
    - hub
