---
apiVersion: v2
name: reloader
description: Umbrella Chart for reloader
type: application
version: 1.0.0
dependencies:
  - name: template-library
    repository: file://../template-library
    version: 0.1.0
  # https://docs.stakater.com/reloader/latest/
  - name: reloader
    repository: https://stakater.github.io/stakater-charts
    version: 2.2.14
