---
apiVersion: kubara.io/v1alpha1
kind: ServiceDefinition
metadata:
  name: external-secrets
  annotations:
    kubara.io/category: security
spec:
  chartPath: external-secrets
  status: enabled
  clusterTypes:
    - controlplane
