---
apiVersion: kubara.io/v1alpha1
kind: ServiceDefinition
metadata:
  name: loki
  annotations:
    kubara.io/category: observability
spec:
  chartPath: loki
  status: enabled
  clusterTypes:
    - controlplane
