---
apiVersion: kubara.io/v1alpha1
kind: ServiceDefinition
metadata:
  name: longhorn
  annotations:
    kubara.io/category: storage
spec:
  chartPath: longhorn
  status: disabled
  clusterTypes:
    - controlplane
