#!/usr/bin/env bash
# Update an existing config.yaml (generated by `kubara init`).
# Strict mode: only modify paths that already exist (clusters[0] only).

set -euo pipefail

die() { printf "✖ %s\n" "$*" >&2; exit 1; }
log() { printf "▶ %s\n" "$*"; }

command -v yq >/dev/null 2>&1 || die "Missing command: yq"

CFG="${1:-}"
[[ -n "$CFG" ]] || die "Usage: .scripts/kubara-config-update.sh <path-to-config.yaml>"
[[ -f "$CFG" ]] || die "config.yaml not found: $CFG"

# If $KUBARA_* is set, set YAML path to the value.
# Fails if the YAML path is missing in the current file.
apply_yaml_if_set() {
  local src_env="$1"    # e.g. KUBARA_SSO_ORG
  local yaml_path="$2"  # e.g. .clusters[0].ssoOrg

  local val="${!src_env:-}"
  [[ -n "$val" ]] || return 0

  local current
  current="$(yq eval "${yaml_path} // \"__MISSING__\"" "$CFG")"
  [[ "$current" == "__MISSING__" ]] \
    && die "YAML path missing in config.yaml: ${yaml_path} (because ${src_env} is set)"

  yq eval "${yaml_path} = \"${val}\"" -i "$CFG"
}

log "Updating config.yaml (strict mode): $CFG"

# Always set type (default hub), but require the path to exist.
TYPE_PATH=".clusters[0].type"
type_current="$(yq eval "${TYPE_PATH} // \"__MISSING__\"" "$CFG")"
[[ "$type_current" == "__MISSING__" ]] && die "YAML path missing in config.yaml: ${TYPE_PATH}"

CLUSTER_TYPE="${KUBARA_CLUSTER_TYPE:-hub}"
yq eval "${TYPE_PATH} = \"${CLUSTER_TYPE}\"" -i "$CFG"

apply_yaml_if_set KUBARA_SSO_ORG             ".clusters[0].ssoOrg"
apply_yaml_if_set KUBARA_SSO_TEAM            ".clusters[0].ssoTeam"
apply_yaml_if_set KUBARA_TERRAFORM_PROVIDER  ".clusters[0].terraform.provider"
apply_yaml_if_set KUBARA_STACKIT_PROJECT_ID  ".clusters[0].terraform.projectId"
apply_yaml_if_set KUBARA_KUBERNETES_TYPE     ".clusters[0].terraform.kubernetesType"
apply_yaml_if_set KUBARA_KUBERNETES_VERSION  ".clusters[0].terraform.kubernetesVersion"

log "✅ config.yaml updated"
