#!/usr/bin/env bash
# Update an existing .env template (generated by `kubara init --prep`).
# Strict template mode: only replace existing keys, never append new ones.

set -euo pipefail

die() { printf "✖ %s\n" "$*" >&2; exit 1; }
log() { printf "▶ %s\n" "$*"; }

command -v sed  >/dev/null 2>&1 || die "Missing command: sed"
command -v grep >/dev/null 2>&1 || die "Missing command: grep"

ENV_FILE="${1:-}"
[[ -n "$ENV_FILE" ]] || die "Usage: .scripts/kubara-env-update.sh <path-to-.env>"
[[ -f "$ENV_FILE" ]] || die ".env not found: $ENV_FILE"

# If $KUBARA_* is set, replace KEY=... with KEY='value' in the existing template.
# Fails if KEY does not exist in the template.
apply_if_set() {
  local src_env="$1"  # e.g. KUBARA_PROJECT_NAME
  local dst_key="$2"  # e.g. PROJECT_NAME

  local val="${!src_env:-}"
  [[ -n "$val" ]] || return 0

  grep -qE "^${dst_key}=" "$ENV_FILE" \
    || die "Template key missing in .env: ${dst_key} (because ${src_env} is set)"

  local escaped="${val//\'/\'\\\'\'}"  # escape single quotes
  sed -i -e "s|^${dst_key}=.*$|${dst_key}='${escaped}'|g" "$ENV_FILE"
}

log "Updating .env (strict mode, no secret output): $ENV_FILE"

# --- KUBARA_* -> .env KEY ---
apply_if_set KUBARA_PROJECT_NAME           PROJECT_NAME
apply_if_set KUBARA_PROJECT_STAGE          PROJECT_STAGE

apply_if_set KUBARA_DOCKERCONFIG_BASE64    DOCKERCONFIG_BASE64

apply_if_set KUBARA_ARGOCD_WIZARD_ACCOUNT_PASSWORD  ARGOCD_WIZARD_ACCOUNT_PASSWORD
apply_if_set KUBARA_ARGOCD_GIT_USERNAME             ARGOCD_GIT_USERNAME
apply_if_set KUBARA_ARGOCD_GIT_PAT_OR_PASSWORD      ARGOCD_GIT_PAT_OR_PASSWORD
apply_if_set KUBARA_ARGOCD_GIT_HTTPS_URL            ARGOCD_GIT_HTTPS_URL
apply_if_set KUBARA_ARGOCD_HELM_REPO_URL            ARGOCD_HELM_REPO_URL
apply_if_set KUBARA_ARGOCD_HELM_REPO_USERNAME       ARGOCD_HELM_REPO_USERNAME
apply_if_set KUBARA_ARGOCD_HELM_REPO_PASSWORD       ARGOCD_HELM_REPO_PASSWORD
# ----------------------------

log "✅ .env updated"
