---
site_name: kubara - Docs
site_url: 'https://docs.kubara.io'
repo_url: 'https://github.com/kubara-io/kubara'
docs_dir: 'content'
nav:
  - Home: index.md
  - Getting Started:
      - Quick Start: 1_getting_started/quick_start.md
      - Installation: 1_getting_started/installation.md
      - Commands: 1_getting_started/commands.md
      - Prerequisites: 1_getting_started/prerequisites.md
      - Bootstrapping: 1_getting_started/bootstrapping.md
      - Providers:
          - STACKIT:
              - Overview: 1_getting_started/providers/stackit.md
              - Terraform Bootstrap: 1_getting_started/providers/stackit_terraform_bootstrap.md
              - Provisioning Infrastructure:
                  - SKE: 1_getting_started/providers/stackit_provisioning_ske.md
                  - Edge Cloud (Beta): 1_getting_started/providers/stackit_provisioning_edgecloud.md
  - Concepts:
      - Overview: 2_concepts/overview_core_concept.md
      - Platform Engineering: 2_concepts/gitops_platform_engineering_idp.md
      - Catalogs: 2_concepts/catalogs.md
      - Catalog Distribution: 2_concepts/catalog_distribution.md
      - Catalog Templating: 2_concepts/catalog_templating.md
  - Building Your Platform:
      - How to add a Spoke Cluster: 3_building_your_platform/add_spoke_cluster.md
      - How to create a Catalog: 3_building_your_platform/create_catalog.md
      - SSO:
          - How to add SSO: 3_building_your_platform/sso/add_sso.md
          - SSO Examples: 3_building_your_platform/sso/add_sso_examples.md
  - Workload Onboarding:
      - Overview: 4_workload_onboarding/overview.md
      - How to add a Project: 4_workload_onboarding/add_app_project.md
      - How to add a Repository: 4_workload_onboarding/add_app_repository.md
      - How to add an AppSet: 4_workload_onboarding/add_appset.md
      - How to add an Application: 4_workload_onboarding/add_application.md
  - Components (Built-in):
      - Overview: 5_components/components_overview.md
      - Best Practices: 5_components/best_practices.md
      - Backup & Recovery: 5_components/backup_and_recovery.md
      - Network:
          - ExternalDNS: 5_components/network_external_dns.md
      - Security:
          - Certificates: 5_components/security_certificates.md
      - Observability:
          - Dashboards: 5_components/observability_dashboards.md
          - Metrics: 5_components/observability_metrics.md
          - Alerts: 5_components/observability_alerts.md
          - Logs: 5_components/observability_logs.md
  - Architecture:
      - Architecture overview: 6_architecture/architecture_overview.md
      - ADR: 9_decisions/ADR.md
      - ADR-Index: 9_decisions/ADR-index.md
  - Community:
      - "Community & Support": 7_community/community-n-support.md
      - Contributing: https://github.com/kubara-io/kubara/blob/main/CONTRIBUTING.md
      - Maintainers: 7_community/maintainers.md
  - Reference:
      - Commands: 1_getting_started/commands.md
      - Release Cycle & Updates: 8_reference/release_cycle_and_updates.md
      - Known Issues: 8_reference/known_issues.md
      - FAQ: 8_reference/faq.md
      - Code of Conduct: https://github.com/kubara-io/kubara/blob/main/CODE_OF_CONDUCT.md
      - Security: https://github.com/kubara-io/kubara/blob/main/SECURITY.md
      - Docs License (CC BY 4.0): https://github.com/kubara-io/kubara/blob/main/NOTICE.md#documentation-license
      - Software License (Apache 2.0): https://github.com/kubara-io/kubara/blob/main/LICENSE
not_in_nav: |
  9_decisions/ADR-template.md
  9_decisions/ADR-[0-9][0-9][0-9][0-9]-*.md
plugins:
  - search
  - privacy:
      assets: false
      links_attr_map:
        target: _blank
  - drawio:
      viewer_js: "js/viewer-static.min.js"
      edit: false
      darkmode: false
markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
# pre-commit yaml linter incompability, works without as well.
#          format: !!python/name:pymdownx.superfences.fence_code_format
theme:
  name: material
  custom_dir: overrides
  logo: images/logo.svg
  favicon: images/favicon.ico
  font: false
  features:
    - search.suggest
    - navigation.sections
    - content.code.copy
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
extra_css:
  - stylesheets/extra.css
# https://jimandreas.github.io/mkdocs-material/reference/variables/
# Set variables as key-value pairs here
extra:
  # This var is used automatically by theme "materials" to enable docs version switching
  version:
    provider: mike
    alias: true
    default: latest-stable
copyright: Copyright &copy; kubara &middot; <a href="https://stackit.com/de/impressum?hidebanner=true">Imprint</a> &middot;
  <a href="https://kubara.io/privacy/">Privacy</a>
strict: true
