---
version: 2
project_name: kubara
before:
  hooks:
    - sh -c 'go-licenses report . --ignore github.com/kubara-io/kubara > licenses.csv'
release:
  github:
    owner: kubara-io
    name: kubara
  draft: true
  replace_existing_draft: true
  replace_existing_artifacts: true
  extra_files:
    - glob: licenses.csv
changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - '^.*?Merge (pull request|branch).*$'
      - '^.*?chore\(release\):.+$'
  groups:
    - title: Breaking changes
      regexp: '^.*?[a-z]+(\([^)]+\))?!:.+$'
      order: 1
    - title: Features
      regexp: '^.*?feat(\([^)]+\))?:.+$'
      order: 10
    - title: Bug fixes
      regexp: '^.*?fix(\([^)]+\))?:.+$'
      order: 20
    - title: Dependency updates
      regexp: '^.*?[a-z]+\((deps[^)]*)\)!?:.+$|^.*?deps(\([^)]+\))?!?:.+$|^.*?bump .+$'
      order: 30
    - title: Documentation
      regexp: '^.*?docs(\([^)]+\))?!?:.+$'
      order: 40
    - title: CI / Build
      regexp: '^.*?(build|ci)(\([^)]+\))?!?:.+$'
      order: 50
    - title: Other changes
      order: 999
builds:
  - id: kubara-linux
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X 'main.version={{ .Tag }}'
      - -X 'main.commit={{ .Commit }}'
      - -X 'main.date={{ .Date }}'
  - id: kubara-windows
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X 'main.version={{ .Tag }}'
      - -X 'main.commit={{ .Commit }}'
      - -X 'main.date={{ .Date }}'
  - id: kubara-macos
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X 'main.version={{ .Tag }}'
      - -X 'main.commit={{ .Commit }}'
      - -X 'main.date={{ .Date }}'
archives:
  - id: windows-archives
    ids:
      - kubara-windows
    formats:
      - zip
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - none*
  - id: unix-archives
    ids:
      - kubara-linux
      - kubara-macos
    formats:
      - tar.gz
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - none*
notarize:
  macos:
      # Whether this configuration is enabled or not.
      #
      # Default: false.
      # Templates: allowed.
    - enabled: '{{ isEnvSet "MACOS_SIGN_P12" }}'

      # IDs to use to filter the built binaries.
      #
      # Default: the project name.
      ids:
        - kubara-macos

      # Before notarizing, we need to sign the binary.
      # This block defines the configuration for doing so.
      sign:
        # The .p12 certificate file path or its base64'd contents.
        #
        # Templates: allowed.
        certificate: "{{.Env.MACOS_SIGN_P12}}"

        # The password to be used to open the certificate.
        #
        # Templates: allowed.
        password: "{{.Env.MACOS_SIGN_PASSWORD}}"

        # Allows to set the signature entitlements XML file.
        #
        # Templates: allowed.
        # entitlements: ./path/to/entitlements.xml

      # Then, we notarize the binaries.
      #
      # You can leave this section empty if you only want
      # to sign the binaries.
      notarize:
        # The issuer ID.
        # Its the UUID you see when creating the App Store Connect key.
        #
        # Templates: allowed.
        issuer_id: "{{.Env.MACOS_NOTARY_ISSUER_ID}}"

        # Key ID.
        # You can see it in the list of App Store Connect Keys.
        # It will also be in the ApiKey filename.
        #
        # Templates: allowed.
        key_id: "{{.Env.MACOS_NOTARY_KEY_ID}}"

        # The .p8 key file path or its base64'd contents.
        #
        # Templates: allowed.
        key: "{{.Env.MACOS_NOTARY_KEY}}"

        # Whether to wait for the notarization to finish.
        # Not recommended, as it could take a really long time.
        wait: true

        # Timeout for the notarization.
        # Beware of the overall `--timeout` time.
        # This only has any effect if `wait` is true.
        #
        # Default: 10m.
        # timeout: 20m
homebrew_casks:
  - name: kubara
    repository:
      owner: kubara-io
      name: homebrew-tap
    description: "Kubara is a single binary CLI tool written in Go providing a lightweight framework for bootstrapping Kubernetes\
      \ platforms with production-proven best practices"
    homepage: "https://github.com/kubara-io/kubara"
    license: "Apache-2.0"
    binaries:
      - kubara
    skip_upload: "auto"
sboms:
  - artifacts: archive
    documents:
      - "{{ .ArtifactName }}.sbom.json"
dockers_v2:
  - dockerfile: ../Dockerfile
    images:
      - "ghcr.io/kubara-io/kubara"
    tags:
      - "{{ .Version }}"
      - "latest"
    sbom: false
nfpms:
  - id: kubara-packages
    ids:
      - kubara-linux
    maintainer: "Kubara Maintainer <kubara@digits.schwarz>"
    formats:
      - deb
