name: docs-check

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'docs/**'
      - '.github/workflows/docs-check.yaml'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: docs-check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kubara repo
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: src/go.mod
          cache: true
          cache-dependency-path: src/go.sum

      - name: Install and setup uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          version: '0.11.15'
          enable-cache: true
          cache-dependency-glob: 'docs/uv.lock'

      - name: Set up Python
        run: |
          cd docs
          uv python install 3.14.3

      - name: Install dependencies
        run: |
          cd docs
          uv sync --frozen

      - name: Validate docs build (strict)
        run: make docs-build

      - name: Check command docs is up to date
        run: |
          if ! git diff --exit-code -- docs; then
            echo "::error::Commands document isn't up to date:"
            echo "::error::Please run 'make docs-build' locally to fix it."
            exit 1
          fi
